# Build stage
FROM golang:1.21.3-alpine AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN apk --no-cache add build-base sqlite-dev \
    && CGO_ENABLED=1 GOOS=linux go build -a -installsuffix cgo -o main .

# Release stage
FROM alpine:latest AS release
WORKDIR /app
COPY --from=build /app/main .
RUN apk --no-cache add dumb-init ca-certificates sqlite
EXPOSE 8000
CMD ["dumb-init", "./main"]
