version: "3.4"
services:
  api:
    restart: unless-stopped
    image: chamanbravo/upstat-api-sqlite:latest
    environment:
      - JWT_SECRET_KEY=asdfjaskljdaq123#!@810248)_+12
    volumes:
      - sqlite_data:/app

  web:
    restart: unless-stopped
    image: chamanbravo/upstat-web:latest
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  sqlite_data:
